import { getNhanVien } from "@/api/phieu-kham-benh-vao-vien";
import { getBenhAnKhoaDieuTri } from "@/api/to-dieu-tri";
import { formatDatetime } from "@/utils/formatters";
import { dsChePhamMaus } from "@/api/benhAnToDieuTri/che-pham-mau";

export const options = {};

async function getBenhAnKhoaDieuTris(params) {
  return await getBenhAnKhoaDieuTri({
    idba: window.location.href.split("/").at(-3),
    huy: false,
    forSelect: true,
    ...params,
  });
}

export const fileds = [
  {
    label: "Khoa",
    type: "select-async",
    fromValue: "khoaDieuTri.stt",
    placeholder: "Chọn khoa",
    action: false,
    keyValue: "stt",
    apiFunc: getBenhAnKhoaDieuTris,
    labelselect: (item) =>
      `${item.khoa.maKhoa} - ${item.khoa.tenKhoa} - ${formatDatetime(
        item.ngayVaoKhoa
      )}`,
    value: "Sttkhoa",
  },
  {
    label: "Ngày chỉ định",
    type: "datetime",
    fromValue: "ngayChiDinh",
    placeholder: "Ngày chỉ định",
    action: false,
    value: "ngayChiDinh",
  },
  {
    label: "Bác sỹ chỉ định",
    type: "select-async",
    fromValue: "bsChiDinh.maNv",
    placeholder: "Chọn bác sỹ chỉ định",
    keyValue: "maNv",
    apiFunc: getNhanVien,
    labelselect: (item) => `${item.maNv}-${item.hoTen}-${item.khoa.tenKhoa}`,
    action: false,
    value: "bsChiDinh",
  },
  {
    label: "Tên chế phẩm máu",
    fromValue: "chePhamMau.maDV",
    placeholder: "Tên chế phẩm máu",
    action: false,
    type: "select-async",
    labelselect: (item) =>
      item.maCpmau + "-" + item.tenCpmau + "-" + item.tenDvt,
    keyValue: "maCpmau",
    apiFunc: dsChePhamMaus,
    value: "maCPM",
  },
  {
    label: "Thể tích",
    type: "number",
    min: 0,
    fromValue: "theTich",
    placeholder: "Thể tích",
    action: true,
    value: "theTich",
    min:0,
    max: 999
  },
  {
    label: "Mã số đơn vị CPM truyền",
    type: "text",
    fromValue: "maSoCmp",
    placeholder: "Mã số đơn vị CPM truyền",
    action: true,
    value: "maSoCmp",
  },
  {
    label: "Ngày điều chế",
    type: "datetime",
    fromValue: "ngayDieuChe",
    placeholder: "Ngày điều chế",
    action: true,
    value: "ngayDieuChe",
  },
  {
    label: "Hạn sử dụng",
    type: "datetime",
    fromValue: "hanSd",
    placeholder: "Hạn sử dụng",
    action: true,
    value: "hanSd",
  },
  {
    label: "Nhóm máu người bệnh:ABO",
    type: "text",
    fromValue: "nhomMau",
    placeholder: "Nhóm máu người bệnh:ABO",
    action: true,
    value: "nhomMau",
  },
  {
    label: "Nhóm máu người bệnh:RhD",
    type: "text",
    fromValue: "rh",
    placeholder: "Nhóm máu người bệnh:RhD",
    action: true,
    value: "rh",
  },
  {
    label: "Nhóm máu chế phẩm ABO",
    type: "text",
    fromValue: "nhomMauCpm",
    placeholder: "Nhóm máu chế phẩm ABO",
    action: true,
    value: "nhomMauCpm",
  },
  {
    label: "Kết quả xét nghiệm hòa hợp: Môi trường muối: Ống 1",
    type: "textarea",
    fromValue: "kqpuhoaHopMuoiOng1",
    placeholder: "Kết quả xét nghiệm hòa hợp: Môi trường muối: Ống 1",
    action: true,
    value: "kqpuhoaHopMuoiOng1",
  },
  {
    label: "Kết quả xét nghiệm hòa hợp: Môi trường muối: Ống 2",
    type: "textarea",
    fromValue: "kqpuhoaHopMuoiOng2",
    placeholder: "Kết quả xét nghiệm hòa hợp: Môi trường muối: Ống 2",
    action: true,
    value: "kqpuhoaHopMuoiOng2",
  },
  {
    label: "Kết quả xét nghiệm hòa hợp: 37 độ/Kháng Globulin:Ống 1",
    type: "textarea",
    fromValue: "kqpuhoaHop37doOng1",
    placeholder: "Kết quả xét nghiệm hòa hợp: 37 độ/Kháng Globulin:Ống 1",
    action: true,
    value: "kqpuhoaHop37doOng1",
  },
  {
    label: "Kết quả xét nghiệm hòa hợp: 37 độ/Kháng Globulin:Ống 2",
    type: "textarea",
    fromValue: "kqpuhoaHop37doOng2",
    placeholder: "Kết quả xét nghiệm hòa hợp: 37 độ/Kháng Globulin:Ống 2",
    action: true,
    value: "kqpuhoaHop37doOng2",
  },
  {
    label: "Kết quả xét nghiệm hòa hợp",
    type: "textarea",
    fromValue: "kqpuhoaHop",
    placeholder: "Kết quả xét nghiệm hòa hợp",
    action: true,
    value: "kqpuhoaHop",
  },
  {
    label: "Tên kết quả xét nghiệm khác",
    type: "textarea",
    fromValue: "tenKqxnkhac",
    placeholder: "Tên kết quả xét nghiệm khác",
    action: true,
    value: "tenKqxnkhac",
  },
  {
    label: "Ngày xét nghiệm",
    type: "datetime",
    fromValue: "ngayXnhoaHop",
    placeholder: "Ngày xét nghiệm",
    action: true,
    value: "ngayXnhoaHop",
  },
  {
    label: "Trưởng khoa XN",
    type: "textarea",
    fromValue: "hoTenTruongKhoaXn",
    placeholder: "Trưởng khoa XN",
    action: true,
    value: "hoTenTruongKhoaXn",
  },
  {
    label: "Người làm xét nghiệm 1",
    type: "textarea",
    fromValue: "hoTenNguoiXn1",
    placeholder: "Người làm xét nghiệm 1",
    action: true,
    value: "hoTenNguoiXn1",
  },
  {
    label: "Người làm xét nghiệm 2",
    type: "textarea",
    fromValue: "hoTenNguoiXn2",
    placeholder: "Người làm xét nghiệm 2",
    action: true,
    value: "hoTenNguoiXn2",
  },
  {
    label: "Lần truyền máu",
    type: "number",
    min: 0,
    max: 255,
    fromValue: "lanTruyenMau",
    placeholder: "Lần truyền máu",
    action: true,
    value: "lanTruyenMau",
  },
  {
    label: "Định nhóm máu chế phẩm tại giường",
    type: "textarea",
    fromValue: "dinhNhomMauChePhamTaiGiuong",
    placeholder: "Định nhóm máu chế phẩm tại giường",
    action: false,
    value: "dinhNhomMauChePhamTaiGiuong",
  },
  {
    label: "Định nhóm máu người bệnh tại giường",
    type: "textarea",
    fromValue: "dinhNhomMauNguoiBenhTaiGiuong",
    placeholder: "Định nhóm máu người bệnh tại giường",
    action: false,
    value: "dinhNhomMauNguoiBenhTaiGiuong",
  },
  {
    label: "Kết quả phản ứng chéo tại giường",
    type: "textarea",
    fromValue: "kqxncheo",
    placeholder: "Kết quả phản ứng chéo tại giường",
    action: true,
    value: "kqxncheo",
  },
  {
    label: "Ngày giờ bắt đầu",
    type: "datetime",
    fromValue: "thoiGianBd",
    placeholder: "Ngày giờ bắt đầu",
    action: true,
    value: "thoiGianBd",
  },
  {
    label: "Ngày giờ kết thúc",
    type: "datetime",
    fromValue: "thoiGianKt",
    placeholder: "Ngày giờ kết thúc",
    action: true,
    value: "thoiGianKt",
  },
  {
    label: "Số lượng máu tryền (ml)",
    type: "number",
    fromValue: "sltruyen",
    placeholder: "Số lượng máu tryền",
    action: true,
    value: "slTruyen",
    unit: "ml",
    min:0,
    max: 999
  },
  {
    label: "Nhận xét quá trình truyền máu",
    type: "textarea",
    fromValue: "nhanXet",
    placeholder: "Nhận xét quá trình truyền máu",
    action: true,
    value: "nhanXet",
  },
  {
    label: "Điều dưỡng",
    type: "select-async",
    fromValue: "dieuDuong.maNv",
    placeholder: "Điều dưỡng",
    keyValue: "maNv",
    apiFunc: getNhanVien,
    labelselect: (item) => `${item.maNv}-${item.hoTen}-${item.khoa.tenKhoa}`,
    action: true,
    value: "dieuDuong",
  },
  {
    label: "Bác sỹ điều trị",
    type: "select-async",
    fromValue: "bstheoDoi.maNv",
    placeholder: "Bác sỹ điều trị",
    keyValue: "maNv",
    apiFunc: getNhanVien,
    labelselect: (item) => `${item.maNv}-${item.hoTen}-${item.khoa.tenKhoa}`,
    action: true,
    value: "bstheoDoi",
  },
];
