import { formatDatetime ,formatDate } from "@/utils/formatters";

export const fileds = [
  {
    text: "stt",
    value: "stt",
    searchValue: "stt",
    showable: true,
    filterable: false,
    filterValue: "stt",
    type: "text",
    sortable: true,
    align: "center",
    width: 100,
  },
  {
    text: "Thời gian",
    type: "datetime",
    showable: true,
    filterable: false,
    value: "thoiGian",
    searchValue: "thoiGian",
    formatter: function (_, __, value) {
      return formatDatetime(value);
    },
    width: 200,
    sortable: true,
    width: 200,
    align: "center",
    form: {
      value: "thoiGian",
      fromValue: "thoiGian",
      default: null,
      type: "datetime",
      creatable: true,
      editable: true,
    },
  },
  {
    text: "Tốc độ truyền",
    value: "tocDo",
    searchValue: "tocDo",
    showable: true,
    filterable: false,
    filterValue: "tocDo",
    type: "text",
    sortable: true,
    align: "center",
    width: 150,
    form: {
      value: "tocDo",
      fromValue: "tocDo",
      default: null,
      type: "text",
      creatable: true,
      editable: true,
    },
  },
  {
    text: "Màu da, niêm mạc",
    value: "mauSacDa",
    searchValue: "mauSacDa",
    showable: true,
    filterable: false,
    filterValue: "mauSacDa",
    type: "text",
    sortable: true,
    align: "center",
    width: 200,
    form: {
      value: "mauSacDa",
      fromValue: "mauSacDa",
      default: null,
      type: "text",
      creatable: true,
      editable: true,
    },
  },
  {
    text: "Nhịp thở",
    value: "nhipTho",
    searchValue: "nhipTho",
    showable: true,
    filterable: false,
    filterValue: "nhipTho",
    type: "text",
    sortable: true,
    align: "center",
    width: 150,
    form: {
      value: "nhipTho",
      fromValue: "nhipTho",
      default: null,
      type: "number",
      creatable: true,
      editable: true,
      rules: [
        {
          validator: (v) => v !== null && v !== undefined,
          message: "Trường này bắt buộc nhập",
        },
        {
          validator: (v) => v > 0,
          message: "Trường này bắt buộc lớn hơn 0",
        },
        {
          validator: (v) => v < 100,
          message: "Trường này bắt buộc nhỏ hơn 100",
        },
      ],
    },
  },
  {
    text: "Mạch",
    value: "mach",
    searchValue: "mach",
    showable: true,
    filterable: false,
    filterValue: "mach",
    type: "text",
    sortable: true,
    align: "center",
    width: 150,
    form: {
      value: "mach",
      fromValue: "mach",
      default: null,
      type: "number",
      creatable: true,
      editable: true,
      rules: [
        {
          validator: (v) => v !== null && v !== undefined,
          message: "Trường này bắt buộc nhập",
        },
        {
          validator: (v) => v > 0,
          message: "Trường này bắt buộc lớn hơn 0",
        },
        {
          validator: (v) => v < 300,
          message: "Trường này bắt buộc nhỏ hơn 300",
        },
      ],
    },
  },
  {
    text: "Nhiệt độ",
    value: "nhietDo",
    searchValue: "nhietDo",
    showable: true,
    filterable: false,
    filterValue: "nhietDo",
    type: "text",
    sortable: true,
    align: "center",
    width: 150,
    form: {
      value: "nhietDo",
      fromValue: "nhietDo",
      default: null,
      type: "number",
      creatable: true,
      editable: true,
      rules: [
        {
          validator: (v) => v !== null && v !== undefined,
          message: "Trường này bắt buộc nhập",
        },
        {
          validator: (v) => v >= 34,
          message: "Trường này bắt buộc lớn hơn 34",
        },
        {
          validator: (v) => v <= 42,
          message: "Trường này bắt buộc nhỏ hơn 42",
        },
      ],
    },
  },
  {
    text: "Huyết áp",
    value: "huyetAp",
    searchValue: "huyetAp",
    showable: true,
    filterable: false,
    filterValue: "huyetAp",
    type: "text",
    sortable: true,
    align: "center",
    width: 150,
    form: {
      value: "huyetAp",
      fromValue: "huyetAp",
      default: null,
      type: "text",
      creatable: true,
      editable: true,
    },
  },
  {
    text: "Diễn biến khác",
    value: "dienBienKhac",
    searchValue: "dienBienKhac",
    showable: true,
    filterable: false,
    filterValue: "dienBienKhac",
    type: "text",
    sortable: true,
    align: "center",
    width: 150,
    form: {
      value: "dienBienKhac",
      fromValue: "dienBienKhac",
      default: null,
      type: "text",
      creatable: true,
      editable: true,
    },
  },
  {
    text: "Ngày lập",
    type: "date",
    showable: true,
    filterable: false,
    value: "ngayLap",
    searchValue: "ngayLap",
    formatter: function (_, __, value) {
      return formatDate(value);
    },
    width: 150,
    sortable: true,
  },
  {
    text: "Người lập",
    type: "text",
    showable: true,
    filterable: false,
    value: "nguoiLap.hoTen",
    searchValue: "nguoiLap",
    filterValue: "nguoiSua",
    width: 150,
    sortable: true,
  },
  {
    text: "Ngày sửa",
    type: "date",
    showable: true,
    filterable: false,
    value: "ngaySd",
    searchValue: "ngaySd",
    filterValue: "ngaySua",
    formatter: function (_, __, value) {
      return formatDate(value);
    },
    width: 150,
    sortable: true,
  },
  {
    text: "Người sửa",
    type: "text",
    showable: true,
    value: "nguoiSD.hoTen",
    searchValue: "nguoiSD",
    filterable: false,
    width: 150,
    sortable: true,
  },
  {
    text: "Hủy",
    type: "text",
    showable: true,
    filterable: false,
    value: "huy",
    searchValue: "huy",
    width: 100,
    type: "boolean",
    align: "center",
    sortable: true,
    form: {
      value: "huy",
      fromValue: "huy",
      default: null,
      type: "boolean",
      creatable: false,
      editable: true,
    },
  },
  {
    text: "Ngày hủy",
    type: "date",
    showable: true,
    filterable: false,
    value: "ngayHuy",
    searchValue: "ngayHuy",
    formatter: function (_, __, value) {
      return formatDate(value);
    },
    width: 150,
    sortable: true,
  },
  {
    text: "Người hủy",
    type: "text",
    showable: true,
    filterable: false,
    value: "nguoiHuy.hoTen",
    searchValue: "nguoiHuy",
    width: 150,
    sortable: true,
  },
 
]

export const actions =["edit","delete","create",]
