export default [
  { text: "Thông tin tờ bệnh án", value: "thong-tin-to-benh-an" },
  {
    text: "Phiếu khám sàng lọc dinh dưỡng",
    value: "phieu-kham-sang-loc-dinh-duong",
  },
  { text: "Phiếu khám bệnh vào viện", value: "phieu-kham-benh-vao-vien" },
  { text: "Tờ điều trị", value: "to-dieu-tri" },
  { text: "Phiếu thử phản ứng thuốc", value: "phieu-thu-phan-ung-thuoc" },
  { text: "Phiếu hội chẩn", value: "phieu-hoi-chan" },
  {
    text: "Phiếu tổng kết 15 ngày điều trị",
    value: "phieu-tong-ket-15-ngay-dieu-tri",
  },
  {
    text: "Tai biến phẫu thuật thủ thuật",
    value: "tai-bien-phau-thuat-thu-thuat",
  },
  { text: "Theo dõi truyền dịch", value: "theo-doi-truyen-dich" },
  { text: "Phiếu chăm sóc", value: "phieu-cham-soc" },
  // { text: "Giấy chuyển tuyến", value: "giay-chuyen-tuyen" },
  { text: "Giấy ra viện", value: "giay-ra-vien" },
  { text: "Biên bản kiểm điểm tử vong", value: "bien-ban-kiem-diem-tu-vong" },
  { text: "Giấy báo tử", value: "giay-bao-tu" },
  {
    text: "Phiếu chẩn đoán nguyên nhân tử vong",
    value: "phieu-chan-doan-nguyen-nhan-tu-vong",
  },
  { text: "Kết quả khám chuyên khoa", value: "can-lam-sang/1" },
  { text: "Kết quả xét nghiệm", value: "ket-qua-xet-nghiem" },
  { text: "Kết quả Chẩn đoán hình ảnh", value: "can-lam-sang/3" },
  { text: "Kết quả thăm dò chức năng", value: "can-lam-sang/4" },
  {
    text: "Phiếu theo dõi truyền máu",
    value: "phieu-theo-doi-truyen-mau",
  },
  // { text: "Phiếu tiếp nhận bệnh nhân", value: "phieu-tiep-nhan-benh-nhan" },
  { text: "Phiếu khám gây mê trước mổ", value: "phieu-kham-gay-me-truoc-mo" },
  { text: "Phiếu phẫu thuật thủ thuật", value: "phieu-phau-thuat-thu-thuat" },
  // { text: "Chỉ định vật lý trị liệu", value: "chi-dinh-vat-ly-tri-lieu" },
];
