using System;
using System.Collections.Generic;
using Medyx.ApiAssets.Models.Interface;

namespace Medyx_EMR_BCA.ApiAssets.Models
{
    public partial class BenhAnKhamBenhYhct : ITrackableIDBA
    {
        public decimal Idba { get; set; }
        public string MaBa { get; set; }
        public string MaBn { get; set; }
        public string HinhThaiVongChan { get; set; }
        public string ThanVongChan { get; set; }
        public string SacVongChan { get; set; }
        public string TrachVongChan { get; set; }
        public string HinhThaiLuoi { get; set; }
        public string ChatLuoi { get; set; }
        public string MoTaKhacVongChan { get; set; }
        public string DuongChiTay { get; set; }
        public string ReuLuoi { get; set; }
        public string TinhChatChiTay { get; set; }
        public string HinhDangChiTay { get; set; }
        public string MauSacChiTay { get; set; }
        public string TiengNoi { get; set; }
        public string HoiTho { get; set; }
        public string CoHo { get; set; }
        public string TinhTrangHo { get; set; }
        public string O { get; set; }
        public string Nac { get; set; }
        public string MuiCoThe { get; set; }
        public string ChatThaiBhbenh { get; set; }
        public string MoTaKhacVanChan { get; set; }
        public string BhbenhHanNhiet { get; set; }
        public string CoBhbenhHanNhiet { get; set; }
        public string MoHoi { get; set; }
        public string BhbenhDauMatCo { get; set; }
        public string DauDau { get; set; }
        public string HoaMat { get; set; }
        public string Mat { get; set; }
        public string Tai { get; set; }
        public string Mui { get; set; }
        public string Hong { get; set; }
        public string CoVai { get; set; }
        public string CoBhbenhLung { get; set; }
        public string BhbenhLung { get; set; }
        public string CoBhbenhNguc { get; set; }
        public string BhbenhNguc { get; set; }
        public string CoBhbenhBung { get; set; }
        public string BhbenhBung { get; set; }
        public string CoBhbenhChanTay { get; set; }
        public string BhbenhChanTay { get; set; }
        public string CoBhbenhAn { get; set; }
        public string BhbenhAn { get; set; }
        public string CoBhbenhUong { get; set; }
        public string ThichUong { get; set; }
        public string CoBhbenhDtt { get; set; }
        public string BhbenhDaiTien { get; set; }
        public string BhbenhTieuTien { get; set; }
        public string CoBhbenhNgu { get; set; }
        public string BhbenhNgu { get; set; }
        public string CoBhbenhSdss { get; set; }
        public string BhbenhSdssnam { get; set; }
        public string BhbenhSdssnu { get; set; }
        public string CoBhbenhKinhNguyet { get; set; }
        public string RoiLoanKinhNguyet { get; set; }
        public string ThongKinh { get; set; }
        public string CoBhbenhDoiHa { get; set; }
        public string BhbenhDoiHa { get; set; }
        public string YeuToXuatHienBenh { get; set; }
        public string MoTaKhacVaanChan { get; set; }
        public string CoBhbenhXucChan { get; set; }
        public string Thop { get; set; }
        public string DaXucChan { get; set; }
        public string CoBhbenhCoXuongKhop { get; set; }
        public string BhbenhCoXuongKhop { get; set; }
        public string CoBhbenhBungXucChan { get; set; }
        public string BhbenhBungXucChan { get; set; }
        public string CoBhbenhMoiHoi { get; set; }
        public string BhbenhMoHoi { get; set; }
        public string MachChan { get; set; }
        public string TongKhanPhai { get; set; }
        public string MaTongKhanPhai { get; set; }
        public string TongKhanTrai { get; set; }
        public string MaTongKhanTrai { get; set; }
        public string ThonTrai { get; set; }
        public string QuanTrai { get; set; }
        public string XichTrai { get; set; }
        public string ThonPhai { get; set; }
        public string QuanPhai { get; set; }
        public string XichPhai { get; set; }
        public string MoTaXucChan { get; set; }
        public string MachPhai { get; set; }
        public string MachTrai { get; set; }
        public string MoTaKhacThietChan { get; set; }
        public string TomTatTuChan { get; set; }
        public string BienChungLuanTri { get; set; }
        public string MaBenhDanhTheoYhct { get; set; }
        public string BatCuong { get; set; }
        public string BhbatCuong { get; set; }
        public string NguyenNhanChanDoan { get; set; }
        public string TangPhu { get; set; }
        public string KinhMach { get; set; }
        public string DinhViBenhTheo { get; set; }
        public byte? DtdonThuanYhct { get; set; }
        public string Ppdtyhct { get; set; }
        public string PhuongDuoc { get; set; }
        public string PpdtkhongDungThuoc { get; set; }
        public string Ppkhac { get; set; }
        public string PhuongHuyet { get; set; }
        public string XoaBopBamHuyet { get; set; }
        public bool? Huy { get; set; }
        public string MaMay { get; set; }
        public DateTime? NgayLap { get; set; }
        public string NguoiLap { get; set; }
        public DateTime? NgaySd { get; set; }
        public string NguoiSd { get; set; }
        public DateTime? NgayHuy { get; set; }
        public string NguoiHuy { get; set; }
    }
}
