// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using Medyx_EMR_BCA.ApiAssets.StoreProcedureModels;

namespace Medyx_EMR_BCA.ApiAssets.StoreProcedureModels
{
    public partial class Medyx_EMR_BCAContext
    {

        [DbFunction("FGIAIMA", "dbo")]
        public static string FGIAIMA(string oldstr)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("FMAHOA", "dbo")]
        public static string FMAHOA(string oldstr)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
