// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Medyx_EMR_BCA.ApiAssets.StoreProcedureModels
{
    public partial class sp_GetAllActionByRoleIDResult
    {
        public long ApplicationRolesActionId { get; set; }
        public string ActionDetailsName { get; set; }
        public int? Status { get; set; }
        public string ActionName { get; set; }
        public long ApplicationActionId { get; set; }
    }
}
