// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Medyx_EMR_BCA.ApiAssets.StoreProcedureModels
{
    public partial class sp_GetAllMenuByUserIDResult
    {
        public string MenuID { get; set; }
        public string MenuName { get; set; }
        public int? Level { get; set; }
        public string MenuParent { get; set; }
        public string ControllerName { get; set; }
        public IEnumerable<sp_GetAllMenuByUserIDResult> Children { get; set; }
    }
}
