// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Medyx_EMR_BCA.ApiAssets.StoreProcedureModels
{
    public partial class spACCOUNT_GetResult
    {
        public string ghichu { get; set; }
        public string MaNV { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string MaKhoaLS { get; set; }
        public string MaKhoaCLS { get; set; }
        public string MaKho { get; set; }
        public bool AllMaKho { get; set; }
        public bool AllMaKhoaCLS { get; set; }
        public bool AllMaKhoaLS { get; set; }
        public string QuyenDTuong { get; set; }
        public bool AllQuyenDTuong { get; set; }
        public string MaMay { get; set; }
        public bool? Huy { get; set; }
        public DateTime NgaySD { get; set; }
        public string NguoiSD { get; set; }
        public bool? Qadmin { get; set; }
        public bool? Qsgia { get; set; }
        public string hoten { get; set; }
        public string tennguoisd { get; set; }
    }
}
