// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Medyx_EMR_BCA.ApiAssets.StoreProcedureModels
{
    public partial class spDMRole_GetAllResult
    {
        public string TenRole { get; set; }
        public string ApplicationRolesId { get; set; }
        public string MaMay { get; set; }
        public bool Huy { get; set; }
        public DateTime NgaySD { get; set; }
        public string NguoiSD { get; set; }
        public string GhiChu { get; set; }
    }
}
