// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Medyx_EMR_BCA.ApiAssets.StoreProcedureModels
{
    public partial class spDMNHANVIEN_GetAllResult
    {
        public string hotendd { get; set; }
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public string MaChucVu { get; set; }
        public string MaLoaiHD { get; set; }
        public string MaChuyenMon { get; set; }
        public string MaKhoa { get; set; }
        public string MaMay { get; set; }
        public bool? Huy { get; set; }
        public string NgaySD { get; set; }
        public string NguoiSD { get; set; }
        public bool? KhongSD { get; set; }
        public string NguoiSD1 { get; set; }
        public string NgaySD1 { get; set; }
        public int? MaQL { get; set; }
        public string MaCD { get; set; }
        public string TenTat { get; set; }
        public string GhiChu { get; set; }
        public string idnhanvien { get; set; }
        public string manv1 { get; set; }
        public string DienThoai { get; set; }
        public string MaChungChiHanhNghe { get; set; }
        public string NguoiGiamHo { get; set; }
        public string DienThoaiKhoa { get; set; }
        public string Chuky { get; set; }
        public string manvtruongkhoa { get; set; }
        public string TENNGUOISD { get; set; }
        public string TENKHOA { get; set; }
        public string TENCHUYENMON { get; set; }
        public string TENCV { get; set; }
        public string TENCD { get; set; }
        public string TenNguoiGiamHo { get; set; }
        public string TENLOAIHD { get; set; }
    }
}
