// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Medyx_EMR_BCA.ApiAssets.StoreProcedureModels
{
    public partial class spDMAction_GetByRoleResult
    {
        public bool? Chon { get; set; }
        public string MaAction { get; set; }
        public string TenAction { get; set; }
        public string buttonName { get; set; }
        public long ApplicationActionId { get; set; }
    }
}
