// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Medyx_EMR_BCA.ApiAssets.StoreProcedureModels
{
    public partial class spDMCHUYENMON_GetAllResult
    {
        public string MaChuyenMon { get; set; }
        public string TenChuyenMon { get; set; }
        public string MaMay { get; set; }
        public byte? Cap { get; set; }
        public string Loai { get; set; }
        public bool? Huy { get; set; }
        public DateTime NgaySD { get; set; }
        public string NguoiSD { get; set; }
        public string GhiChu { get; set; }
        public string idparent { get; set; }
    }
}
