// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Medyx_EMR_BCA.ApiAssets.StoreProcedureModels
{
    public partial class spDMCHUCVU_CREATEResult
    {
    }
}
