// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Medyx_EMR_BCA.ApiAssets.StoreProcedureModels
{
    public partial class spDMRole_UpdateResult
    {
        public bool Chon { get; set; }
        public string MaAction { get; set; }
        public string TenAction { get; set; }
        public string ButtonName { get; set; }
        public string ApplicationActionId { get; set; }
    }
}
