export const form = {
  an: null,
  hoaMat:null,
  batCuong: null,
  bhan: null,
  bhbatCuong: null,
  bhbung: null,
  bhbungXucChan: null,
  bhchanTay: null,
  bhcoXuongKhop: null,
  bhdaiTieuTien: null,
  bhdauMatCo: null,
  bhdoiHa: null,
  bhhanNhiet: null,
  bhkn: null,
  bhlung: null,
  bhmat: null,
  bhmoHoi: null,
  bhngu: null,
  bhnguc: null,
  bhuong: null,
  bhxucChan: null,
  bienChungLuanTri: null,
  bung: null,
  chanTay: null,
  chatLuoi: null,
  coChatThaiBenhLy: null,
  coHo: null,
  coMui: null,
  coVai: null,
  daiTien: null,
  dauDau: null,
  dinhViBenhTheo: null,
  dkxhbenh: null,
  doiHa: null,
  dtdonThuanYhct: null,
  giongNoi: null,
  hannhiet: null,
  hinhThaiLuoi: null,
  hinhThaiVongChan: null,
  ho: null,
  hoiTho: null,
  hong: null,
  huy: null,
  idba: null,
  kieuChatThai: null,
  kieuMui: null,
  kinhMach: null,
  lung: null,
  maBa: null,
  maBenhDanhTheoYhct: null,
  maBn: null,
  maMay: null,
  machChan: null,
  machPhai: null,
  machTrai: null,
  mat: null,
  moHoi: null,
  moTaDinhViBenhTheo: null,
  moTaKinhMach: null,
  moTaNguyenNhan: null,
  moTaTangPhu: null,
  moTaVanChan: null,
  moTaVongChan: null,
  moTaXucChan: null,
  mtthietChan: null,
  mtvaanChan: null,
  moTaVanChan:null,
  mui: null,
  nacAmThanh: null,
  ngayHuy: null,
  ngayLap: null,
  ngaySd: null,
  ngu: null,
  nguc: null,
  nguoiHuy: null,
  nguoiLap: null,
  nguoiSd: null,
  nguyenNhan: null,
  oamThanh: null,
  phuongHuyet: null,
  reuLuoi: null,
  rlkinhnguyet: null,
  rlknsinhDuc: null,
  rlnam: null,
  rlnu: null,
  sacVongChan: null,
  tai: null,
  tangPhu: null,
  thanVongChan: null,
  thongKinh: null,
  tieuTien: null,
  tomTatTuChan: null,
  tongKhanPhai: null,
  tongKhanTrai: null,
  trachVongChan: null,
  uong: null,
  viKhanPhaiQuan: null,
  viKhanPhaiThon: null,
  viKhanPhaiXich: null,
  viKhanTraiQuan: null,
  viKhanTraiThon: null,
  viKhanTraiXich: null,
  xoaBopBamHuyet: null,
  xucChanBung: null,
  xucChanCoXuongKhop: null,
  xucChanDa: null,
  xucChanMoHoi: null,
};

export const checkBoxData = {
  hinhThaiVongChans: [
    { ten: "Gầy", checkbox: false },
    { ten: "Béo", checkbox: false },
    { ten: "Cân đối", checkbox: false },
    { ten: "Nằm co", checkbox: false },
    { ten: "Nằm duỗi", checkbox: false },
    { ten: "Ưa tĩnh", checkbox: false },
    { ten: "Ưa động", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  ThanVongChans: [
    { ten: "Còn thần", checkbox: false },
    { ten: "Không còn thần", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  SacVongChan: [
    { ten: "Bệch (trắng)", checkbox: false },
    { ten: "Đỏ", checkbox: false },
    { ten: "Vàng", checkbox: false },
    { ten: "Xanh", checkbox: false },
    { ten: "Đen", checkbox: false },
    { ten: "Bình thường", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  TrachVongChan: [
    { ten: "Tươi Nhuận", checkbox: false },
    { ten: "Khô", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],

  HinhThaiLuoi: [
    { ten: "Bình thường", checkbox: false },
    { ten: "Lệch", checkbox: false },
    { ten: "Rụt", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  chatLuoi: [
    { ten: "Đạm", checkbox: false },
    { ten: "Bệu", checkbox: false },
    { ten: "Gầy mỏng", checkbox: false },
    { ten: "Nứt", checkbox: false },
    { ten: "Cứng", checkbox: false },
    { ten: "Loét", checkbox: false },
    { ten: "Hồng", checkbox: false },
    { ten: "Nhợt", checkbox: false },
    { ten: "Đỏ", checkbox: false },
    { ten: "Đỏ sẫm", checkbox: false },
    { ten: "Tím", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  reuLuoi: [
    { ten: "Có", checkbox: false },
    { ten: "Không", checkbox: false },
    { ten: "Bong", checkbox: false },
    { ten: "Dầy", checkbox: false },
    { ten: "Mỏng", checkbox: false },
    { ten: "Ướt", checkbox: false },
    { ten: "Khô", checkbox: false },
    { ten: "Nhuật", checkbox: false },
    { ten: "Dính", checkbox: false },
    { ten: "Trắng", checkbox: false },
    { ten: "Vàng", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  tiengNoi: [
    { ten: "Bình thường", checkbox: false },
    { ten: "To", checkbox: false },
    { ten: "Nhỏ", checkbox: false },
    { ten: "Đứt quãng", checkbox: false },
    { ten: "Khàn", checkbox: false },
    { ten: "Ngọng", checkbox: false },
    { ten: "Mất", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  hoiTho: [
    { ten: "Bình thường", checkbox: false },
    { ten: "Đứt quãng", checkbox: false },
    { ten: "Ngắn", checkbox: false },
    { ten: "Mạnh", checkbox: false },
    { ten: "Yếu", checkbox: false },
    { ten: "Thô", checkbox: false },
    { ten: "Rít", checkbox: false },
    { ten: "Khò khè", checkbox: false },
    { ten: "Chậm", checkbox: false },
    { ten: "Gấp", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  TinhTrangHo: [
    { ten: "Ho liên tục", checkbox: false },
    { ten: "Cơn", checkbox: false },
    { ten: "Ít", checkbox: false },
    { ten: "Nhiều", checkbox: false },
    { ten: "Khan", checkbox: false },
    { ten: "Có đờm", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  muiCoThe: [
    { ten: "Chua", checkbox: false },
    { ten: "Khắm", checkbox: false },
    { ten: "Tanh", checkbox: false },
    { ten: "Thối", checkbox: false },
    { ten: "Hôi", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  chatThai: [
    { ten: "Đờm", checkbox: false },
    { ten: "Chất nôn", checkbox: false },
    { ten: "Phân", checkbox: false },
    { ten: "Nước tiểu", checkbox: false },
    { ten: "Khí hư", checkbox: false },
    { ten: "Kinh nguyệt", checkbox: false },
  ],
  hanNhiet: [
    { ten: "Thích nóng", checkbox: false },
    { ten: "Sợ nóng", checkbox: false },
    { ten: "Thích mát", checkbox: false },
    { ten: "Sợ lạnh", checkbox: false },
    { ten: "Trong người nóng", checkbox: false },
    { ten: "Trong người lạnh", checkbox: false },
    { ten: "Rét run", checkbox: false },
    { ten: "Hàn nhiệt vãng lai", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  moHoi: [
    { ten: "Bình thường", checkbox: false },
    { ten: "Không có mồ hôi", checkbox: false },
    { ten: "Tự hãn", checkbox: false },
    { ten: "Đạo hãn", checkbox: false },
    { ten: "Nhiều", checkbox: false },
    { ten: "Ít", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  dauDau: [
    { ten: "Một chỗ", checkbox: false },
    { ten: "Nửa đầu", checkbox: false },
    { ten: "Cả đầu", checkbox: false },
    { ten: "Di chuyển", checkbox: false },
    { ten: "Ê ẩm", checkbox: false },
    { ten: "Nhói", checkbox: false },
    { ten: "Căng", checkbox: false },
    { ten: "Nặng đầu", checkbox: false },
    { ten: "Đau nhói", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  mat: [
    { ten: "Nhìn không rõ", checkbox: false },
    { ten: "Đau", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  tai: [
    { ten: "Ù", checkbox: false },
    { ten: "Điếc", checkbox: false },
    { ten: "Đau", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  mui: [
    { ten: "Ngạt", checkbox: false },
    { ten: "Chảy nước", checkbox: false },
    { ten: "Chảy máu cam", checkbox: false },
    { ten: "Đau", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  hong: [
    { ten: "Đau", checkbox: false },
    { ten: "Khô", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  coVai: [
    { ten: "Mỏi", checkbox: false },
    { ten: "Đau", checkbox: false },
    { ten: "Khó vận động", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  Lung: [
    { ten: "Mỏi lưng", checkbox: false },
    { ten: "Đau", checkbox: false },
    { ten: "Khó vận động", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  Nguc: [
    { ten: "Tức", checkbox: false },
    { ten: "Đau", checkbox: false },
    { ten: "Ngột ngạt khó thở", checkbox: false },
    { ten: "Đau tức cạnh sườn", checkbox: false },
    { ten: "Đánh trống lồng ngực", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  Bung: [
    { ten: "Đau", checkbox: false },
    { ten: "Sôi bụng", checkbox: false },
    { ten: "Nóng ruột", checkbox: false },
    { ten: "Đầy trướng", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  chanTay: [
    { ten: "Đau", checkbox: false },
    { ten: "Tê", checkbox: false },
    { ten: "Buồn", checkbox: false },
    { ten: "Mỏi", checkbox: false },
    { ten: "Nhức", checkbox: false },
    { ten: "Nóng", checkbox: false },
    { ten: "Lạnh", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  An: [
    { ten: "Thích nóng", checkbox: false },
    { ten: "Thích mát", checkbox: false },
    { ten: "Ăn nhiều", checkbox: false },
    { ten: "Ăn ít", checkbox: false },
    { ten: "Đắng miệng", checkbox: false },
    { ten: "Nhạt miệng", checkbox: false },
    { ten: "Thèm ăn", checkbox: false },
    { ten: "Chán ăn", checkbox: false },
    { ten: "Ăn vào chướng bụng", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  Uong: [
    { ten: "Mát", checkbox: false },
    { ten: "Ấm nóng", checkbox: false },
    { ten: "Nhiều", checkbox: false },
    { ten: "Ít", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  daiTien: [
    { ten: "Vàng", checkbox: false },
    { ten: "Đỏ", checkbox: false },
    { ten: "Đục", checkbox: false },
    { ten: "Buốt", checkbox: false },
    { ten: "Rắt", checkbox: false },
    { ten: "Không tự chủ", checkbox: false },
    { ten: "Bí", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  tieuTien: [
    { ten: "Táo", checkbox: false },
    { ten: "Nát", checkbox: false },
    { ten: "Sõng", checkbox: false },
    { ten: "Lỏng", checkbox: false },
    { ten: "Nhầy mũi", checkbox: false },
    { ten: "Bí", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  Ngu: [
    { ten: "Khó vào giấc", checkbox: false },
    { ten: "Hay tỉnh", checkbox: false },
    { ten: "Hay mê", checkbox: false },
    { ten: "Ngủ ít", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  namGioi: [
    { ten: "Liệt dương", checkbox: false },
    { ten: "Di tinh", checkbox: false },
    { ten: "Hoạt tinh", checkbox: false },
    { ten: "Mộng tinh", checkbox: false },
    { ten: "Lãnh tinh", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  nuGioi: [
    { ten: "Vô sinh", checkbox: false },
    { ten: "Động thai", checkbox: false },
    { ten: "Sảy thai", checkbox: false },
    { ten: "Sảy thai liên tiếp", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  roiLoanKinhNguyet: [
    { ten: "Trước kì", checkbox: false },
    { ten: "Sau kì", checkbox: false },
    { ten: "Bế kinh", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  thongKinh: [
    { ten: "Trước kì", checkbox: false },
    { ten: "Trong kì", checkbox: false },
    { ten: "Sau kì", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  doiHa: [
    { ten: "Vàng", checkbox: false },
    { ten: "Trắng", checkbox: false },
    { ten: "Hồng", checkbox: false },
    { ten: "Hôi", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  daXucChan: [
    { ten: "Khô", checkbox: false },
    { ten: "Nóng", checkbox: false },
    { ten: "Lạnh", checkbox: false },
    { ten: "Ướt", checkbox: false },
    { ten: "Tay chân nóng", checkbox: false },
    { ten: "Tay chân lạnh", checkbox: false },
    { ten: "Ấn lõm", checkbox: false },
    { ten: "Ấn đau", checkbox: false },
    { ten: "U cục", checkbox: false },
  ],
  coXuongKhopXucChan: [
    { ten: "Mềm nhẽo", checkbox: false },
    { ten: "Căng cứng", checkbox: false },
    { ten: "Ấn đau", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  bungXucChan: [
    { ten: "Chướng", checkbox: false },
    { ten: "Tích", checkbox: false },
    { ten: "Tụ", checkbox: false },
    { ten: "Thiện án", checkbox: false },
    { ten: "Cự án", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  moHoiXucChan: [
    { ten: "Toàn thân", checkbox: false },
    { ten: "Trán", checkbox: false },
    { ten: "Tay", checkbox: false },
    { ten: "Chân", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  machChan: [
    { ten: "Trầm", checkbox: false },
    { ten: "Trì", checkbox: false },
    { ten: "Phù", checkbox: false },
    { ten: "Sác", checkbox: false },
    { ten: "Hoạt", checkbox: false },
    { ten: "Huyền", checkbox: false },
    { ten: "Nhu", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  machChanTrai: [
    { ten: "Trầm", checkbox: false },
    { ten: "Trì", checkbox: false },
    { ten: "Phù", checkbox: false },
    { ten: "Sác", checkbox: false },
    { ten: "Hoạt", checkbox: false },
    { ten: "Huyền", checkbox: false },
    { ten: "Nhu", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  machChanPhai: [
    { ten: "Trầm", checkbox: false },
    { ten: "Trì", checkbox: false },
    { ten: "Phù", checkbox: false },
    { ten: "Sác", checkbox: false },
    { ten: "Hoạt", checkbox: false },
    { ten: "Huyền", checkbox: false },
    { ten: "Nhu", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  machChanThonTrai: [
    { ten: "Trầm", checkbox: false },
    { ten: "Trì", checkbox: false },
    { ten: "Phù", checkbox: false },
    { ten: "Sác", checkbox: false },
    { ten: "Hoạt", checkbox: false },
    { ten: "Huyền", checkbox: false },
    { ten: "Nhu", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  machChanQuanTrai: [
    { ten: "Trầm", checkbox: false },
    { ten: "Trì", checkbox: false },
    { ten: "Phù", checkbox: false },
    { ten: "Sác", checkbox: false },
    { ten: "Hoạt", checkbox: false },
    { ten: "Huyền", checkbox: false },
    { ten: "Nhu", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  machChanXichTrai: [
    { ten: "Trầm", checkbox: false },
    { ten: "Trì", checkbox: false },
    { ten: "Phù", checkbox: false },
    { ten: "Sác", checkbox: false },
    { ten: "Hoạt", checkbox: false },
    { ten: "Huyền", checkbox: false },
    { ten: "Nhu", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  machChanThonPhai: [
    { ten: "Trầm", checkbox: false },
    { ten: "Trì", checkbox: false },
    { ten: "Phù", checkbox: false },
    { ten: "Sác", checkbox: false },
    { ten: "Hoạt", checkbox: false },
    { ten: "Huyền", checkbox: false },
    { ten: "Nhu", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  machChanQuanPhai: [
    { ten: "Trầm", checkbox: false },
    { ten: "Trì", checkbox: false },
    { ten: "Phù", checkbox: false },
    { ten: "Sác", checkbox: false },
    { ten: "Hoạt", checkbox: false },
    { ten: "Huyền", checkbox: false },
    { ten: "Nhu", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  machChanXichPhai: [
    { ten: "Trầm", checkbox: false },
    { ten: "Trì", checkbox: false },
    { ten: "Phù", checkbox: false },
    { ten: "Sác", checkbox: false },
    { ten: "Hoạt", checkbox: false },
    { ten: "Huyền", checkbox: false },
    { ten: "Nhu", checkbox: false },
    { ten: "Khác", checkbox: false },
  ],
  batCuong: [
    { ten: "Biểu", checkbox: false },
    { ten: "Lý", checkbox: false },
    { ten: "Hư", checkbox: false },
    { ten: "Thực", checkbox: false },
    { ten: "Hàn", checkbox: false },
    { ten: "Nhiệt", checkbox: false },
    { ten: "Âm", checkbox: false },
    { ten: "Dương", checkbox: false },
  ],
  nguyenNhan: [
    { ten: "Nội nhân", checkbox: false },
    { ten: "Ngoại nhân", checkbox: false },
    { ten: "Bất nội ngoại nhân", checkbox: false },
  ],
  tangPhu: [
    { ten: "Tâm", checkbox: false },
    { ten: "Can", checkbox: false },
    { ten: "Tỳ", checkbox: false },
    { ten: "Phế", checkbox: false },
    { ten: "Thận", checkbox: false },
    { ten: "Tâm bào", checkbox: false },
    { ten: "Tiều trường", checkbox: false },
    { ten: "Đờm", checkbox: false },
    { ten: "Vị", checkbox: false },
    { ten: "Đại trường", checkbox: false },
    { ten: "Bàng quang", checkbox: false },
    { ten: "Tam tiêu", checkbox: false },
    { ten: "Phù kì hằng", checkbox: false },
  ],
  kinhMach: [
    { ten: "Tâm", checkbox: false },
    { ten: "Can", checkbox: false },
    { ten: "Tỳ", checkbox: false },
    { ten: "Phế", checkbox: false },
    { ten: "Thận", checkbox: false },
    { ten: "Tâm bào", checkbox: false },
    { ten: "Tiều trường", checkbox: false },
    { ten: "Đờm", checkbox: false },
    { ten: "Vị", checkbox: false },
    { ten: "Đại trường", checkbox: false },
    { ten: "Bàng quang", checkbox: false },
    { ten: "Tam tiêu", checkbox: false },
    { ten: "Mạch đốc", checkbox: false },
    { ten: "Mạch nhâm", checkbox: false },
  ],
  dinhViBenhTheo: [
    { ten: "Vệ", checkbox: false },
    { ten: "Khí", checkbox: false },
    { ten: "Dinh", checkbox: false },
    { ten: "Huyết", checkbox: false },
  ],
};

export const danhMucData = [
  {
    MaParent: "045",
    TenParent: "HinhThaiVongChan",
    Model: "hinhThaiVongChan",
    Data: "hinhThaiVongChans",
  },
  {
    MaParent: "046",
    TenParent: "ThanVongChan",
    Model: "thanVongChan",
    Data: "ThanVongChans",
  },
  {
    MaParent: "047",
    TenParent: "SacVongChan",
    Model: "sacVongChan",
    Data: "SacVongChan",
  },
  {
    MaParent: "048",
    TenParent: "TrachVongChan",
    Model: "trachVongChan",
    Data: "TrachVongChan",
  },
  {
    MaParent: "049",
    TenParent: "HinhThaiLuoi",
    Model: "hinhThaiLuoi",
    Data: "HinhThaiLuoi",
  },
  {
    MaParent: "050",
    TenParent: "ChatLuoi",
    Model: "chatLuoi",
    Data: "chatLuoi",
  },
  {
    MaParent: "051",
    TenParent: "ReuLuoi",
    Model: "reuLuoi",
    Data: "reuLuoi",
  },
  {
    MaParent: "056",
    TenParent: "TiengNoi",
    Model: "giongNoi",
    Data: "tiengNoi",
  },
  {
    MaParent: "057",
    TenParent: "HoiTho",
    Model: "hoiTho",
    Data: "hoiTho",
  },
  {
    MaParent: "059",
    TenParent: "TinhTrangHo",
    Model: "ho",
    Data: "TinhTrangHo",
  },
  {
    MaParent: "063",
    TenParent: "MuiCoThe",
    Model: "kieuMui",
    Data: "muiCoThe",
  },
  {
    MaParent: "065",
    TenParent: "ChatThaiBHBL",
    Model: "kieuChatThai",
    Data: "chatThai",
  },
  {
    MaParent: "067",
    TenParent: "BHHanNhiet",
    Model: "hannhiet",
    Data: "hanNhiet",
  },
  {
    MaParent: "068",
    TenParent: "MoHoi",
    Model: "moHoi",
    Data: "moHoi",
  },
  {
    MaParent: "070",
    TenParent: "DauDau",
    Model: "dauDau",
    Data: "dauDau",
  },
  {
    MaParent: "072",
    TenParent: "Mat",
    Model: "mat",
    Data: "mat",
  },
  {
    MaParent: "073",
    TenParent: "Tai",
    Model: "tai",
    Data: "tai",
  },
  {
    MaParent: "074",
    TenParent: "Mui",
    Model: "mui",
    Data: "mui",
  },
  {
    MaParent: "075",
    TenParent: "Hong",
    Model: "hong",
    Data: "hong",
  },
  {
    MaParent: "076",
    TenParent: "CoVai",
    Model: "coVai",
    Data: "coVai",
  },
  {
    MaParent: "078",
    TenParent: "BHBLLung",
    Model: "lung",
    Data: "Lung",
  },
  {
    MaParent: "080",
    TenParent: "BHBLNguc",
    Model: "nguc",
    Data: "Nguc",
  },
  {
    MaParent: "082",
    TenParent: "BHBLBung",
    Model: "bung",
    Data: "Bung",
  },
  {
    MaParent: "084",
    TenParent: "BHBLChanTay",
    Model: "chanTay",
    Data: "chanTay",
  },
  {
    MaParent: "086",
    TenParent: "BHBLAn",
    Model: "an",
    Data: "An",
  },
  {
    MaParent: "088",
    TenParent: "ThichUong",
    Model: "uong",
    Data: "Uong",
  },
  {
    MaParent: "091",
    TenParent: "BHBLDaiTien",
    Model: "daiTien",
    Data: "daiTien",
  },
  {
    MaParent: "090",
    TenParent: "BHBLTieuTien",
    Model: "tieuTien",
    Data: "tieuTien",
  },
  {
    MaParent: "093",
    TenParent: "BHBLNgu",
    Model: "ngu",
    Data: "Ngu",
  },
  {
    MaParent: "095",
    TenParent: "BHKNSDSSNam",
    Model: "rlnam",
    Data: "namGioi",
  },
  {
    MaParent: "096",
    TenParent: "BHKNSDSSNu",
    Model: "rlnu",
    Data: "nuGioi",
  },
  {
    MaParent: "098",
    TenParent: "RLKinhNguyet",
    Model: "rlkinhnguyet",
    Data: "roiLoanKinhNguyet",
  },
  {
    MaParent: "099",
    TenParent: "ThongKinh",
    Model: "thongKinh",
    Data: "thongKinh",
  },
  {
    MaParent: "101",
    TenParent: "BHBLDoiHa",
    Model: "doiHa",
    Data: "doiHa",
  },
  {
    MaParent: "105",
    TenParent: "DaXucChan",
    Model: "xucChanDa",
    Data: "daXucChan",
  },
  {
    MaParent: "107",
    TenParent: "BHBLCoXuongKhop",
    Model: "xucChanCoXuongKhop",
    Data: "coXuongKhopXucChan",
  },
  {
    MaParent: "109",
    TenParent: "BHBLBungXucChan",
    Model: "xucChanBung",
    Data: "bungXucChan",
  },
  {
    MaParent: "111",
    TenParent: "BHBLMoHoiXucChan",
    Model: "xucChanMoHoi",
    Data: "moHoiXucChan",
  },
  {
    MaParent: "112",
    TenParent: "MachChan",
    Model: "machChan",
    Data: "machChan",
  },
  {
    MaParent: "114",
    TenParent: "TongKhanTrai",
    Model: "tongKhanTrai",
    Data: "machChanTrai",
  },
  {
    MaParent: "113",
    TenParent: "TongKhanPhai",
    Model: "tongKhanPhai",
    Data: "machChanPhai",
  },
  {
    MaParent: "115",
    TenParent: "ThonTrai",
    Model: "viKhanTraiThon",
    Data: "machChanThonTrai",
  },
  {
    MaParent: "116",
    TenParent: "QuanTrai",
    Model: "viKhanTraiQuan",
    Data: "machChanQuanTrai",
  },
  {
    MaParent: "117",
    TenParent: "XichTrai",
    Model: "viKhanTraiXich",
    Data: "machChanXichTrai",
  },
  {
    MaParent: "118",
    TenParent: "ThonPhai",
    Model: "viKhanPhaiThon",
    Data: "machChanThonPhai",
  },
  {
    MaParent: "119",
    TenParent: "QuanPhai",
    Model: "viKhanPhaiQuan",
    Data: "machChanQuanPhai",
  },
  {
    MaParent: "120",
    TenParent: "XichPhai",
    Model: "viKhanPhaiXich",
    Data: "machChanXichPhai",
  },
  {
    MaParent: "124",
    TenParent: "KinhMach",
    Model: "kinhMach",
    Data: "kinhMach",
  },
  {
    MaParent: "121",
    TenParent: "BHBatCuong",
    Model: "bhbatCuong",
    Data: "batCuong",
  },
  {
    MaParent: "122",
    TenParent: "NguyenNhanChanDoan",
    Model: "nguyenNhan",
    Data: "nguyenNhan",
  },
  {
    MaParent: "123",
    TenParent: "TangPhu",
    Model: "tangPhu",
    Data: "tangPhu",
  },
  {
    MaParent: "125",
    TenParent: "DinhViBenh",
    Model: "dinhViBenhTheo",
    Data: "dinhViBenhTheo",
  },
];

